name: Sync to Gist
on:
  push:
    branches:
      - main
jobs:
  sync-to-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Sync to Gist
        env:
          GIST_ACCESS_TOKEN: ${{ secrets.GIST_ACCESS_TOKEN }}
        run: |
          echo "Syncing files to Gist..."
          node sync-to-gist.js
